const OPTIONS={
 modelType:['functional part','miniature','display object','support test','tolerance test','surface-finish test','overhang test','bridging test','speed test','material test','prototype','jig/fixture','art object','replacement part','calibration object','other'],
 printerModels:['Bambu Lab X2D','Bambu Lab X2D Combo','Bambu Lab X1 Carbon','Bambu Lab X1E','Bambu Lab P1S','Bambu Lab P1P','Bambu Lab A1','Bambu Lab A1 mini','Other'],
 profiles:['0.20mm Standard @BBL X2D','0.16mm Optimal @BBL X2D','0.12mm Fine @BBL X2D','0.08mm Extra Fine @BBL X2D','0.24mm Draft @BBL X2D','0.28mm Extra Draft @BBL X2D','0.20mm Strength @BBL X2D','0.20mm Support @BBL X2D','0.20mm Standard - PLA Basic','0.20mm Standard - PETG Basic','0.20mm Standard - TPU 95A','0.20mm Standard - ABS/ASA','0.20mm Standard - Support Interface Test','0.20mm Standard - Dual Nozzle Support Test','Custom profile'],
 brands:['Bambu Lab','Polymaker','Hatchbox','Overture','eSUN','MatterHackers','Prusament','Sunlu','Elegoo','Inland','Atomic Filament','Cookiecad','ColorFabb','Proto-pasta','Fillamentum','Fiberlogy','Amolen','Anycubic','Creality','Flashforge','Giantarm','IIID Max','Numakers','Paramount 3D','RePKord','SainSmart','Sovol','Ziro','Other'],
 material:['PLA Basic','PLA Matte','PLA Silk','PLA Metal','PLA Marble','PLA Wood','PLA Glow','PLA Galaxy','PLA Tough','PLA Aero','PLA+','PETG Basic','PETG HF','PETG Translucent','PETG-CF','TPU 95A','TPU 85A','ABS','ABS-GF','ASA','ASA-CF','PA','PA6','PA12','PA-CF','PA-GF','PC','PC-CF','PVA Support','BVOH Support','HIPS Support','Bambu Support for PLA/PETG','Bambu Support for PA/PET','Breakaway support','Other'],
 colors:['Black','White','Gray','Light Gray','Dark Gray','Silver','Red','Orange','Yellow','Green','Blue','Indigo','Violet','Purple','Pink','Magenta','Cyan','Teal','Brown','Tan','Beige','Ivory','Natural','Clear','Translucent','Gold','Copper','Bronze','Rainbow','Multi-color','Glow','Marble','Wood tone','Custom color','Other'],
 condition:['new','dry','recently dried','questionable','wet/stringy','old spool','unknown'],
 nozzle:['0.2 mm','0.25 mm','0.3 mm','0.4 mm','0.5 mm','0.6 mm','0.8 mm','1.0 mm','Auxiliary support nozzle','other'],
 plates:['Textured PEI Plate','Smooth PEI Plate','Cool Plate','High Temperature Plate','Engineering Plate','SuperTack Plate','Dual-Sided Textured PEI Plate','PEO/PEI Pattern Plate','G10/Garolite Plate','Glass Plate','Third-party PEI plate','Other'],
 adhesive:['none','Bambu liquid glue','glue stick','liquid glue','hairspray','Magigoo','Nano polymer adhesive','blue painter tape','Kapton tape','other'],
 status:['success','partial success','failed','cancelled'],
 failure:['none','bed adhesion','spaghetti','clog','under-extrusion','over-extrusion','warping','layer shift','poor supports','support scarring','stringing','rough surface','dimensional inaccuracy','elephant foot','heat creep','nozzle collision','AMS/feed issue','filament tangle','other'],
 noteTags:['idea','problem','setting to test','filament issue','maintenance','support issue','surface finish','dimensional accuracy','bed adhesion','AMS','nozzle','build plate','slicer profile'],
 maint:['nozzle change','plate cleaning','filament dried','AMS issue','calibration','lubrication','belt check','firmware note','extruder cleaning','hotend cleaning','carbon rod cleaning','lead screw lubrication','camera/lidar check','other']
};const SETTINGS={
 Quality:['Layer height','Initial layer height','Line width','Wall generator','Wall loops','Top shell layers','Bottom shell layers','Seam position','Ironing','Fuzzy skin','Arc fitting'],
 Strength:['Sparse infill density','Sparse infill pattern','Internal solid infill pattern','Wall order','Infill/wall overlap','Top/bottom thickness'],
 Speed:['Outer wall speed','Inner wall speed','Sparse infill speed','Top surface speed','Travel speed','Initial layer speed','Acceleration','Jerk','Silent mode / speed mode'],
 Support:['Supports enabled','Support type','Tree supports','Support threshold angle','Support top Z distance','Support bottom Z distance','Support interface','Support interface pattern','Support/object XY distance','Support critical regions only','Support removal notes'],
 Filament:['Nozzle temperature','Bed temperature','Volumetric speed','Flow ratio','Pressure advance / flow dynamics','Retraction length','Retraction speed','Cooling fan speed','Auxiliary fan','Chamber fan','Filament drying notes'],
 Cooling:['Part cooling fan','Minimum layer time','Slow down for overhangs','Fan speed for overhangs','Bridge fan speed'],
 Adhesion:['Brim','Brim width','Skirt','Raft','Initial layer temperature','Initial layer speed','Plate cleaning method'],
 Special:['Adaptive layers','Variable layer height','Multi-material settings','Prime tower','Flush volume','Timelapse setting','Arachne/classic wall behavior','Custom G-code','Other setting']
};
const SCORES=['overallPrintQuality','surfaceFinish','dimensionalAccuracy','strength','detailResolution','supportRemoval','bedAdhesion','stringingControl','overhangPerformance','bridgingPerformance','easeOfCleanup','useAgain'];
const scoreLabels={overallPrintQuality:'Overall print quality',surfaceFinish:'Surface finish',dimensionalAccuracy:'Dimensional accuracy',strength:'Strength',detailResolution:'Detail resolution',supportRemoval:'Support removal',bedAdhesion:'Bed adhesion',stringingControl:'Stringing control',overhangPerformance:'Overhang performance',bridgingPerformance:'Bridging performance',easeOfCleanup:'Ease of cleanup',useAgain:'Would I use these settings again?'};
let experiments=[],photos=[],notes=[],maintenance=[]; let stagedPhotos=[];
const $=id=>document.getElementById(id);

document.addEventListener('DOMContentLoaded',init);
async function init(){await openDb(); hydrateUi(); bindEvents(); await refreshAll(); if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
function hydrateUi(){
 fill('modelType',OPTIONS.modelType); fillDataList('printerModels',OPTIONS.printerModels); fillDataList('studioProfiles',OPTIONS.profiles); fillDataList('filamentBrands',OPTIONS.brands); fillDataList('filamentMaterials',OPTIONS.material); fillDataList('filamentColors',OPTIONS.colors); fillDataList('nozzleSizes',OPTIONS.nozzle); fillDataList('buildPlates',OPTIONS.plates); fill('filamentCondition',OPTIONS.condition); fill('bedAdhesive',OPTIONS.adhesive); fill('resultStatus',OPTIONS.status); fill('failureType',OPTIONS.failure); fill('noteTag',OPTIONS.noteTags); fill('maintType',OPTIONS.maint); enhanceTypeOrSelectFields();
 setX2DDefaults(); $('dateTime').value=new Date().toISOString().slice(0,16); $('maintDate').value=new Date().toISOString().slice(0,10);
 $('settingsChanged').innerHTML=Object.entries(SETTINGS).map(([cat,items])=>`<details><summary><strong>${cat}</strong></summary>${items.map(name=>`<div class="setting-row" data-category="${cat}" data-name="${name}"><label><input type="checkbox" class="setting-check"> ${name}</label><input class="old-val" placeholder="Old value"><input class="new-val" placeholder="New value"><input class="setting-note" placeholder="Notes"></div>`).join('')}</details>`).join('');
 $('scoreSliders').innerHTML=SCORES.map(k=>`<label class="score-row">${scoreLabels[k]} <output id="out-${k}">5</output><input data-score="${k}" type="range" min="1" max="10" value="5"></label>`).join('');
 document.querySelectorAll('[data-score]').forEach(r=>r.addEventListener('input',()=>$('out-'+r.dataset.score).textContent=r.value));
}
function fill(id,arr){$(id).innerHTML=arr.map(x=>`<option>${x}</option>`).join('')}
function fillDataList(id,arr){$(id).innerHTML=arr.map(x=>`<option value="${escapeHtml(x)}"></option>`).join('')}
function enhanceTypeOrSelectFields(){
 const map=[
  ['printerModel','Printer model options',OPTIONS.printerModels],
  ['profileName','Bambu Studio profile options',OPTIONS.profiles],
  ['filamentBrand','Filament brand options',OPTIONS.brands],
  ['filamentMaterial','Filament/material profile options',OPTIONS.material],
  ['filamentColor','Filament color options',OPTIONS.colors],
  ['nozzleSize','Nozzle size options',OPTIONS.nozzle],
  ['buildPlate','Build plate options',OPTIONS.plates]
 ];
 for(const [inputId,label,options] of map){
  const input=$(inputId);
  if(!input || input.dataset.enhanced==='true') continue;
  input.dataset.enhanced='true';
  const select=document.createElement('select');
  select.className='combo-select';
  select.title=`Open ${label.toLowerCase()} and copy one into the editable text field above`;
  select.innerHTML='<option value="">Choose from common options…</option>'+options.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');
  select.addEventListener('change',()=>{ if(select.value){ input.value=select.value; input.dispatchEvent(new Event('input',{bubbles:true})); } });
  input.insertAdjacentElement('afterend',select);
 }
}
function setX2DDefaults(){ $('printerModel').value='Bambu Lab X2D'; $('profileName').value='0.20mm Standard @BBL X2D'; $('filamentBrand').value='Bambu Lab'; $('filamentMaterial').value='PLA Basic'; $('filamentColor').value='Black'; $('filamentCondition').value='dry'; $('nozzleSize').value='0.4 mm'; $('buildPlate').value='Textured PEI Plate'; $('bedAdhesive').value='none'; $('amsUsed').value='No'; $('dualMaterial').value='No'; $('supportMaterial').value='No'; $('resultStatus').value='success'; $('failureType').value='none'; }
function bindEvents(){
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab)); document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.jump));
 $('themeToggle').onclick=()=>{document.body.dataset.theme=document.body.dataset.theme==='dark'?'':'dark'; localStorage.setItem('bplt-theme',document.body.dataset.theme||'light'); renderCharts(experiments); const a=experiments.find(e=>e.id===$('compareA')?.value), b=experiments.find(e=>e.id===$('compareB')?.value); if(a&&b&&$('compareRadar')) renderCompareRadar(a,b);}; document.body.dataset.theme=localStorage.getItem('bplt-theme')==='dark'?'dark':'';
 $('experimentForm').onsubmit=saveExperiment; $('resetForm').onclick=resetForm; $('photoInput').onchange=stageExperimentPhotos;
 ['searchBox','filterMaterial','filterStatus','filterCategory','sortBy'].forEach(id=>$(id).oninput=renderExperimentList);
 $('runCompare').onclick=runCompare; $('noteForm').onsubmit=saveNote; $('maintenanceForm').onsubmit=saveMaintenance;
 $('exportJson').onclick=downloadBackup; $('quickExportA').onclick=downloadBackup; $('importJson').onchange=importBackup; $('loadSamples').onclick=loadSampleData; $('clearSamples').onclick=clearSampleData; $('clearAll').onclick=clearAllData;
}
function showTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id)); if(id==='experiments') renderExperimentList(); if(id==='dashboard') renderDashboard();}
async function refreshAll(){experiments=await getAll('experiments'); photos=await getAll('photos'); notes=await getAll('notes'); maintenance=await getAll('maintenance'); renderAll();}
function renderAll(){populateFilters(); renderDashboard(); renderExperimentList(); renderSelectors(); renderNotes(); renderMaintenance(); renderLastBackup();}
function populateFilters(){
 const mat=[...new Set(experiments.map(e=>e.filament.material).filter(Boolean))]; $('filterMaterial').innerHTML='<option value="">All materials</option>'+mat.map(x=>`<option>${x}</option>`).join(''); $('filterStatus').innerHTML='<option value="">All statuses</option>'+OPTIONS.status.map(x=>`<option>${x}</option>`).join(''); $('filterCategory').innerHTML='<option value="">All setting categories</option>'+Object.keys(SETTINGS).map(x=>`<option>${x}</option>`).join('');
}
function renderSelectors(){const opts='<option value="">Choose experiment</option>'+experiments.map(e=>`<option value="${e.id}">${escapeHtml(e.title)} — ${new Date(e.dateTime||e.createdAt).toLocaleDateString()}</option>`).join(''); ['compareA','compareB','noteExperiment','maintExperiment'].forEach(id=>$(id).innerHTML=(id.includes('compare')?opts:'<option value="">None</option>'+opts.replace('<option value="">Choose experiment</option>','')));}
function getPhoto(id){return photos.find(p=>p.id===id)}
function thumbFor(e){const p=getPhoto((e.photoIds||[])[0]);return p?p.dataUrl:''}
function renderDashboard(){
 const total=experiments.length, statuses=countBy(experiments,e=>e.result.status||'unknown'), mats=countBy(experiments,e=>e.filament.material||'unknown');
 const avgScore=avg(experiments.map(e=>+e.scores.overallPrintQuality||0)).toFixed(1), avgSupport=avg(experiments.map(e=>+e.scores.supportRemoval||0)).toFixed(1), avgSurface=avg(experiments.map(e=>+e.scores.surfaceFinish||0)).toFixed(1);
 const cats={}; experiments.forEach(e=>(e.settingsChanged||[]).forEach(s=>cats[s.category]=(cats[s.category]||0)+1));
 const most=o=>Object.entries(o).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';
 $('kpiGrid').innerHTML=[['Total',total],['Success',statuses.success||0],['Partial',(statuses['partial success']||0)],['Failed',statuses.failed||0],['Avg quality',avgScore],['Avg support removal',avgSupport],['Avg surface finish',avgSurface],['Most-used filament',most(mats)],['Most-tested category',most(cats)]].map(([a,b])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong></div>`).join('');
 const best=[...experiments].sort((a,b)=>(+b.scores.overallPrintQuality||0)-(+a.scores.overallPrintQuality||0))[0]; $('bestCard').innerHTML=best?`<strong>${escapeHtml(best.title)}</strong><p>${best.filament.material||''} · ${best.hardware.nozzleSize||''}</p><p>Overall score: <strong>${best.scores.overallPrintQuality}/10</strong></p><button title="Open the best scoring experiment" onclick="viewExperiment('${best.id}')">View</button>`:'No experiments yet.';
 $('recentExperiments').innerHTML=[...experiments].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5).map(miniCard).join('')||'<p class="muted">No experiments yet.</p>'; renderCharts(experiments);
}
function miniCard(e){return `<div class="pill">${escapeHtml(e.title)} · ${e.filament.material||'material?'} · ${e.scores.overallPrintQuality}/10</div>`}
function renderExperimentList(){
 let arr=[...experiments]; const q=$('searchBox').value.toLowerCase(), mat=$('filterMaterial').value, st=$('filterStatus').value, cat=$('filterCategory').value, sort=$('sortBy').value;
 if(q) arr=arr.filter(e=>JSON.stringify(e).toLowerCase().includes(q)); if(mat) arr=arr.filter(e=>e.filament.material===mat); if(st) arr=arr.filter(e=>e.result.status===st); if(cat) arr=arr.filter(e=>(e.settingsChanged||[]).some(s=>s.category===cat));
 arr.sort((a,b)=>sort==='oldest'?new Date(a.createdAt)-new Date(b.createdAt):sort==='highest'?(+b.scores.overallPrintQuality)-(+a.scores.overallPrintQuality):sort==='lowest'?(+a.scores.overallPrintQuality)-(+b.scores.overallPrintQuality):sort==='material'?(a.filament.material||'').localeCompare(b.filament.material||''):sort==='status'?(a.result.status||'').localeCompare(b.result.status||''):new Date(b.createdAt)-new Date(a.createdAt));
 $('experimentList').innerHTML=arr.map(experimentCard).join('')||'<article class="card"><p>No experiments found.</p></article>';
}
function experimentCard(e){const t=thumbFor(e); const cls=e.result.status==='success'?'success':e.result.status==='failed'?'fail':'warn';return `<article class="card experiment-card"><img class="thumb" src="${t||''}" alt=""><div><h3>${escapeHtml(e.title)} ${e.isBaseline?'<span class="pill">Baseline</span>':''}</h3><p class="muted">${new Date(e.dateTime||e.createdAt).toLocaleString()} · ${e.filament.material||'—'} · ${e.hardware.nozzleSize||'—'} · <span class="${cls}">${e.result.status}</span></p><p>Score: <strong>${e.scores.overallPrintQuality}/10</strong></p><p>${(e.settingsChanged||[]).slice(0,4).map(s=>`<span class="pill">${s.category}: ${escapeHtml(s.name)}</span>`).join('')}</p><div class="card-actions"><button title="Open the full experiment detail view" onclick="viewExperiment('${e.id}')">View</button><button title="Edit this experiment" onclick="editExperiment('${e.id}')">Edit</button><button title="Create a new experiment using this one as a starting point" onclick="duplicateExperiment('${e.id}')">Duplicate</button><button title="Mark this as a known-good baseline for comparisons" onclick="markBaseline('${e.id}')">Baseline</button><button title="Delete this experiment permanently from local storage" class="danger" onclick="deleteExperiment('${e.id}')">Delete</button></div></div></article>`}
async function stageExperimentPhotos(){for(const file of $('photoInput').files){const dataUrl=await imageToDataUrl(file); stagedPhotos.push({id:uuid(),dataUrl,caption:'',createdAt:new Date().toISOString()});} renderStagedPhotos();}
function renderStagedPhotos(){ $('photoPreview').innerHTML=stagedPhotos.map((p,i)=>`<div><img src="${p.dataUrl}"><input placeholder="Caption" value="${escapeHtml(p.caption||'')}" oninput="stagedPhotos[${i}].caption=this.value"><button type="button" title="Remove this staged photo before saving" onclick="stagedPhotos.splice(${i},1);renderStagedPhotos()">Remove</button></div>`).join('');}
async function saveExperiment(ev){ev.preventDefault(); const id=$('experimentId').value||uuid(); const now=new Date().toISOString(); const existing=experiments.find(e=>e.id===id); stagedPhotos.forEach(p=>p.experimentId=id); for(const p of stagedPhotos) await put('photos',p);
 const e={id,createdAt:existing?.createdAt||now,updatedAt:now,dateTime:$('dateTime').value?new Date($('dateTime').value).toISOString():now,title:$('title').value.trim(),printerModel:$('printerModel').value,bambuStudioProfile:$('profileName').value,modelName:$('modelName').value,modelType:$('modelType').value,filament:{brand:$('filamentBrand').value,material:$('filamentMaterial').value,color:$('filamentColor').value,condition:$('filamentCondition').value},hardware:{nozzleSize:$('nozzleSize').value,buildPlate:$('buildPlate').value,bedAdhesive:$('bedAdhesive').value,amsUsed:$('amsUsed').value,dualMaterial:$('dualMaterial').value,supportMaterial:$('supportMaterial').value,estimatedTime:$('estimatedTime').value,actualTime:$('actualTime').value,filamentUsed:$('filamentUsed').value},result:{status:$('resultStatus').value,failureType:$('failureType').value},settingsChanged:collectSettings(),scores:collectScores(),notes:{improved:$('improved').value,worse:$('worse').value,surprised:$('surprised').value,nextTest:$('nextTest').value,general:$('generalNotes').value},photoIds:[...(existing?.photoIds||[]),...stagedPhotos.map(p=>p.id)],tags:[],isBaseline:existing?.isBaseline||false,baselineName:existing?.baselineName||''};
 await put('experiments',e); resetForm(); await refreshAll(); showTab('experiments');}
function collectSettings(){return [...document.querySelectorAll('.setting-row')].filter(r=>r.querySelector('.setting-check').checked).map(r=>({category:r.dataset.category,name:r.dataset.name,oldValue:r.querySelector('.old-val').value,newValue:r.querySelector('.new-val').value,notes:r.querySelector('.setting-note').value}));}
function collectScores(){const o={}; document.querySelectorAll('[data-score]').forEach(r=>o[r.dataset.score]=+r.value); return o;}
function resetForm(){ $('experimentForm').reset(); $('experimentId').value=''; $('formTitle').textContent='New Experiment'; setX2DDefaults(); $('dateTime').value=new Date().toISOString().slice(0,16); stagedPhotos=[]; renderStagedPhotos(); document.querySelectorAll('[data-score]').forEach(r=>{r.value=5;$('out-'+r.dataset.score).textContent=5}); document.querySelectorAll('.setting-check').forEach(c=>c.checked=false); document.querySelectorAll('.old-val,.new-val,.setting-note').forEach(i=>i.value='');}
async function viewExperiment(id){const e=experiments.find(x=>x.id===id); if(!e) return; const imgs=(e.photoIds||[]).map(getPhoto).filter(Boolean).map(p=>`<figure><img src="${p.dataUrl}" style="max-width:100%;border-radius:12px"><figcaption>${escapeHtml(p.caption||'')}</figcaption></figure>`).join(''); $('detailContent').innerHTML=`<h2>${escapeHtml(e.title)}</h2><p class="muted">${new Date(e.dateTime||e.createdAt).toLocaleString()} · ${e.printerModel}</p><p><strong>${e.filament.material}</strong> ${e.filament.brand||''} · ${e.hardware.nozzleSize||''} · ${e.result.status}</p><h3>Changed settings</h3>${(e.settingsChanged||[]).map(s=>`<p><strong>${s.category}: ${escapeHtml(s.name)}</strong><br>Old: ${escapeHtml(s.oldValue||'—')} · New: ${escapeHtml(s.newValue||'—')}<br>${escapeHtml(s.notes||'')}</p>`).join('')||'None logged.'}<h3>Scores</h3>${Object.entries(e.scores).map(([k,v])=>`<span class="pill">${scoreLabels[k]||k}: ${v}/10</span>`).join('')}<h3>Notes</h3><p>${escapeHtml(Object.values(e.notes||{}).filter(Boolean).join('\n\n'))}</p><h3>Photos</h3><div class="photo-grid">${imgs}</div>`; $('detailDialog').showModal();}
function editExperiment(id){const e=experiments.find(x=>x.id===id); if(!e) return; showTab('newExperiment'); $('formTitle').textContent='Edit Experiment'; $('experimentId').value=e.id; $('title').value=e.title; $('dateTime').value=(e.dateTime||e.createdAt).slice(0,16); $('printerModel').value=e.printerModel||'Bambu Lab X2D'; $('profileName').value=e.bambuStudioProfile||'0.20mm Standard @BBL X2D'; $('modelName').value=e.modelName||''; $('modelType').value=e.modelType||OPTIONS.modelType[0]; $('filamentBrand').value=e.filament.brand||'Bambu Lab'; $('filamentMaterial').value=e.filament.material||'PLA Basic'; $('filamentColor').value=e.filament.color||'Black'; $('filamentCondition').value=e.filament.condition||'unknown'; $('nozzleSize').value=e.hardware.nozzleSize||'0.4 mm'; $('buildPlate').value=e.hardware.buildPlate||'Textured PEI Plate'; $('bedAdhesive').value=e.hardware.bedAdhesive||'none'; $('amsUsed').value=e.hardware.amsUsed||'No'; $('dualMaterial').value=e.hardware.dualMaterial||'No'; $('supportMaterial').value=e.hardware.supportMaterial||'No'; $('estimatedTime').value=e.hardware.estimatedTime||''; $('actualTime').value=e.hardware.actualTime||''; $('filamentUsed').value=e.hardware.filamentUsed||''; $('resultStatus').value=e.result.status||'success'; $('failureType').value=e.result.failureType||'none'; Object.entries(e.notes||{}).forEach(([k,v])=>{const map={general:'generalNotes'}; if($(map[k]||k)) $(map[k]||k).value=v}); document.querySelectorAll('.setting-row').forEach(r=>{const s=(e.settingsChanged||[]).find(x=>x.category===r.dataset.category&&x.name===r.dataset.name); r.querySelector('.setting-check').checked=!!s; r.querySelector('.old-val').value=s?.oldValue||''; r.querySelector('.new-val').value=s?.newValue||''; r.querySelector('.setting-note').value=s?.notes||'';}); Object.entries(e.scores||{}).forEach(([k,v])=>{const r=document.querySelector(`[data-score="${k}"]`); if(r){r.value=v;$('out-'+k).textContent=v}});}
async function duplicateExperiment(id){const e=structuredClone(experiments.find(x=>x.id===id)); if(!e) return; e.id=uuid(); e.title=e.title+' copy'; e.createdAt=e.updatedAt=new Date().toISOString(); e.isBaseline=false; e.baselineName=''; await put('experiments',e); await refreshAll();}
async function markBaseline(id){const e=experiments.find(x=>x.id===id); const name=prompt('Baseline name:',e.baselineName||e.title); if(!name) return; e.isBaseline=true; e.baselineName=name; e.updatedAt=new Date().toISOString(); await put('experiments',e); await refreshAll();}
async function deleteExperiment(id){if(!confirm('Delete this experiment?')) return; await del('experiments',id); await refreshAll();}
function runCompare(){const a=experiments.find(e=>e.id===$('compareA').value), b=experiments.find(e=>e.id===$('compareB').value); if(!a||!b) return; const scoreRows=SCORES.map(k=>{const d=(+b.scores[k]||0)-(+a.scores[k]||0); return `<tr><td>${scoreLabels[k]}</td><td>${a.scores[k]}</td><td>${b.scores[k]}</td><td class="${d>0?'diff-good':d<0?'diff-bad':''}">${d>0?'+':''}${d}</td></tr>`}).join(''); const changedB=(b.settingsChanged||[]).map(s=>s.name); const changedA=(a.settingsChanged||[]).map(s=>s.name); const unique=[...new Set([...changedA,...changedB])]; const summary=summarizeCompare(a,b); $('compareOutput').innerHTML=`<article class="card"><h3>Summary</h3><p>${summary}</p><canvas id="compareRadar" style="max-height:360px"></canvas></article><div class="compare-grid"><article class="card"><h3>${escapeHtml(a.title)}</h3>${experimentFacts(a)}</article><article class="card"><h3>${escapeHtml(b.title)}</h3>${experimentFacts(b)}</article></div><article class="card"><h3>Score Differences</h3><table><tbody>${scoreRows}</tbody></table></article><article class="card"><h3>Setting Differences</h3>${unique.map(n=>`<span class="pill">${escapeHtml(n)}</span>`).join('')}</article>`; renderCompareRadar(a,b);}
function experimentFacts(e){return `<p>${e.filament.material} · ${e.hardware.nozzleSize} · ${e.result.status}</p><p>Changed: ${(e.settingsChanged||[]).map(s=>s.category+': '+s.name).join(', ')||'none'}</p>`}
function summarizeCompare(a,b){const oq=(+b.scores.overallPrintQuality||0)-(+a.scores.overallPrintQuality||0), sr=(+b.scores.supportRemoval||0)-(+a.scores.supportRemoval||0), sf=(+b.scores.surfaceFinish||0)-(+a.scores.surfaceFinish||0); const changed=(b.settingsChanged||[]).slice(0,4).map(s=>s.name).join(', ')||'no logged settings'; return `${b.title} changed overall quality by ${oq>0?'+':''}${oq}, surface finish by ${sf>0?'+':''}${sf}, and support removal by ${sr>0?'+':''}${sr} compared with ${a.title}. Major logged changes in the second experiment: ${changed}.`;}
async function saveNote(ev){ev.preventDefault(); let photoId=''; if($('notePhoto').files[0]){const p={id:uuid(),dataUrl:await imageToDataUrl($('notePhoto').files[0]),createdAt:new Date().toISOString()}; await put('photos',p); photoId=p.id;} await put('notes',{id:uuid(),createdAt:new Date().toISOString(),tag:$('noteTag').value,experimentId:$('noteExperiment').value,text:$('noteText').value,photoId}); $('noteForm').reset(); await refreshAll();}
function renderNotes(){ $('notesList').innerHTML=notes.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(n=>`<article class="card"><span class="pill">${n.tag}</span><p>${escapeHtml(n.text)}</p><p class="muted">${new Date(n.createdAt).toLocaleString()}</p></article>`).join('')||'<p class="muted">No notes yet.</p>';}
async function saveMaintenance(ev){ev.preventDefault(); let photoId=''; if($('maintPhoto').files[0]){const p={id:uuid(),dataUrl:await imageToDataUrl($('maintPhoto').files[0]),createdAt:new Date().toISOString()}; await put('photos',p); photoId=p.id;} await put('maintenance',{id:uuid(),createdAt:new Date().toISOString(),date:$('maintDate').value,type:$('maintType').value,experimentId:$('maintExperiment').value,notes:$('maintNotes').value,photoId}); $('maintenanceForm').reset(); $('maintDate').value=new Date().toISOString().slice(0,10); await refreshAll();}
function renderMaintenance(){ $('maintenanceList').innerHTML=maintenance.sort((a,b)=>new Date(b.date)-new Date(a.date)).map(m=>`<article class="card"><h3>${m.type}</h3><p>${escapeHtml(m.notes||'')}</p><p class="muted">${m.date}</p></article>`).join('')||'<p class="muted">No maintenance logged.</p>';}
async function downloadBackup(){const data=await exportAllData(); const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='bambu-print-lab-backup-'+new Date().toISOString().slice(0,10)+'.json'; a.click(); await refreshAll();}
async function importBackup(ev){const f=ev.target.files[0]; if(!f) return; const data=JSON.parse(await f.text()); const mode=confirm('Replace existing data? Click Cancel to merge instead.')?'replace':'merge'; await importAllData(data,mode); await refreshAll(); alert('Import complete.');}
async function renderLastBackup(){const x=await getOne('appSettings','lastBackup'); $('lastBackup').textContent=x?`Last backup: ${new Date(x.value).toLocaleString()}`:'No backup recorded yet.';}
async function loadSampleData(){const samples=sampleExperiments(); for(const e of samples) await put('experiments',e); await refreshAll();}
async function clearSampleData(){for(const e of experiments.filter(e=>e.sample)) await del('experiments',e.id); await refreshAll();}
async function clearAllData(){if(!confirm('This will erase all local tracker data in this browser. Continue?')) return; for(const s of STORES) await clearStore(s); await refreshAll();}
function sampleExperiments(){const now=Date.now(); return [
 sample('PLA support test','PLA','0.4 mm','partial success',7,'Support','Support top Z distance'), sample('PETG support interface test','PETG','0.4 mm','success',8,'Support','Support interface pattern'), sample('Miniature detail test','PLA','0.2 mm','success',9,'Quality','Layer height'), sample('Surface finish test','PLA+','0.4 mm','success',8,'Quality','Ironing'), sample('Failed adhesion test','ABS','0.6 mm','failed',3,'Adhesion','Brim')
 ].map((e,i)=>({...e,dateTime:new Date(now-i*86400000).toISOString()}));}
function sample(title,mat,nozzle,status,score,cat,set){return {id:uuid(),sample:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),dateTime:new Date().toISOString(),title,printerModel:'Bambu Lab X2D',bambuStudioProfile:'0.20mm Standard @BBL X2D',modelName:title,modelType:'support test',filament:{brand:'Bambu Lab',material:mat,color:'Black',condition:'dry'},hardware:{nozzleSize:nozzle,buildPlate:'Textured PEI',bedAdhesive:'none',amsUsed:'No',dualMaterial:'No',supportMaterial:'No'},result:{status,failureType:status==='failed'?'bed adhesion':'none'},settingsChanged:[{category:cat,name:set,oldValue:'default',newValue:'test value',notes:'sample'}],scores:Object.fromEntries(SCORES.map(k=>[k,score])),notes:{general:'Sample experiment.'},photoIds:[],tags:[],isBaseline:false,baselineName:''};}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
